# Generated by Django 4.1.5 on 2023-01-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
