# Generated by Django 4.1.5 on 2023-01-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('mean', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'теория',
                'verbose_name_plural': 'Теория',
            },
        ),
    ]
