# Generated by Django 4.1.5 on 2023-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massive',
            name='source',
            field=models.CharField(default=1, max_length=250, verbose_name='Ключ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='massive',
            name='name',
            field=models.CharField(default='Урок', max_length=250, verbose_name='Название'),
        ),
    ]
